import { canvasNode, canvasEdge } from "@/types/canvas";

export interface CanvasTemplate {
  id: string;
  name: string;
  description: string;
  nodes: canvasNode[];
  edges: canvasEdge[];
}

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: "microservices",
    name: "Microservices Architecture",
    description: "A standard web client connecting through an API Gateway to multiple backend services backed by databases.",
    nodes: [
      {
        id: "web-client",
        type: "canvas",
        position: { x: 100, y: 200 },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
        data: { label: "Web Client", shape: "pill", color: "blue" },
      },
      {
        id: "api-gateway",
        type: "canvas",
        position: { x: 300, y: 180 },
        width: 100,
        height: 90,
        style: { width: 100, height: 90 },
        data: { label: "API Gateway", shape: "hexagon", color: "purple" },
      },
      {
        id: "auth-service",
        type: "canvas",
        position: { x: 500, y: 50 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Auth Service", shape: "rectangle", color: "amber" },
      },
      {
        id: "user-service",
        type: "canvas",
        position: { x: 500, y: 180 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "User Service", shape: "rectangle", color: "green" },
      },
      {
        id: "order-service",
        type: "canvas",
        position: { x: 500, y: 310 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Order Service", shape: "rectangle", color: "cyan" },
      },
      {
        id: "users-db",
        type: "canvas",
        position: { x: 720, y: 155 },
        width: 90,
        height: 110,
        style: { width: 90, height: 110 },
        data: { label: "Users DB", shape: "cylinder", color: "default" },
      },
      {
        id: "orders-db",
        type: "canvas",
        position: { x: 720, y: 285 },
        width: 90,
        height: 110,
        style: { width: 90, height: 110 },
        data: { label: "Orders DB", shape: "cylinder", color: "default" },
      },
    ],
    edges: [
      {
        id: "e-web-gateway",
        source: "web-client",
        target: "api-gateway",
        type: "canvasEdge",
      },
      {
        id: "e-gateway-auth",
        source: "api-gateway",
        target: "auth-service",
        type: "canvasEdge",
      },
      {
        id: "e-gateway-user",
        source: "api-gateway",
        target: "user-service",
        type: "canvasEdge",
      },
      {
        id: "e-gateway-order",
        source: "api-gateway",
        target: "order-service",
        type: "canvasEdge",
      },
      {
        id: "e-user-db",
        source: "user-service",
        target: "users-db",
        type: "canvasEdge",
      },
      {
        id: "e-order-db",
        source: "order-service",
        target: "orders-db",
        type: "canvasEdge",
      },
    ],
  },
  {
    id: "cicd-pipeline",
    name: "CI/CD Deployment Pipeline",
    description: "A continuous integration and continuous deployment sequence from code commit to production.",
    nodes: [
      {
        id: "commit",
        type: "canvas",
        position: { x: 50, y: 110 },
        width: 80,
        height: 80,
        style: { width: 80, height: 80 },
        data: { label: "Git Commit", shape: "circle", color: "default" },
      },
      {
        id: "github-repo",
        type: "canvas",
        position: { x: 200, y: 120 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "GitHub Repo", shape: "rectangle", color: "blue" },
      },
      {
        id: "ci-pipeline",
        type: "canvas",
        position: { x: 380, y: 105 },
        width: 100,
        height: 90,
        style: { width: 100, height: 90 },
        data: { label: "CI Runner", shape: "hexagon", color: "purple" },
      },
      {
        id: "run-tests",
        type: "canvas",
        position: { x: 540, y: 125 },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
        data: { label: "Run Tests", shape: "pill", color: "amber" },
      },
      {
        id: "docker-build",
        type: "canvas",
        position: { x: 720, y: 120 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Docker Build", shape: "rectangle", color: "cyan" },
      },
      {
        id: "registry",
        type: "canvas",
        position: { x: 900, y: 95 },
        width: 90,
        height: 110,
        style: { width: 90, height: 110 },
        data: { label: "Registry", shape: "cylinder", color: "rose" },
      },
      {
        id: "deploy-prod",
        type: "canvas",
        position: { x: 1050, y: 105 },
        width: 100,
        height: 90,
        style: { width: 100, height: 90 },
        data: { label: "Deploy Prod", shape: "hexagon", color: "green" },
      },
    ],
    edges: [
      {
        id: "e-commit-github",
        source: "commit",
        target: "github-repo",
        type: "canvasEdge",
      },
      {
        id: "e-github-ci",
        source: "github-repo",
        target: "ci-pipeline",
        type: "canvasEdge",
      },
      {
        id: "e-ci-tests",
        source: "ci-pipeline",
        target: "run-tests",
        type: "canvasEdge",
      },
      {
        id: "e-tests-build",
        source: "run-tests",
        target: "docker-build",
        type: "canvasEdge",
      },
      {
        id: "e-build-registry",
        source: "docker-build",
        target: "registry",
        type: "canvasEdge",
      },
      {
        id: "e-registry-deploy",
        source: "registry",
        target: "deploy-prod",
        type: "canvasEdge",
      },
    ],
  },
  {
    id: "event-driven",
    name: "Event-Driven System",
    description: "An event publisher broadcasting messages through a central message broker to subscribing processing workloads.",
    nodes: [
      {
        id: "publisher",
        type: "canvas",
        position: { x: 80, y: 180 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Event Publisher", shape: "rectangle", color: "blue" },
      },
      {
        id: "broker",
        type: "canvas",
        position: { x: 280, y: 155 },
        width: 90,
        height: 110,
        style: { width: 90, height: 110 },
        data: { label: "Kafka Broker", shape: "cylinder", color: "amber" },
      },
      {
        id: "processor-a",
        type: "canvas",
        position: { x: 470, y: 80 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Processor A", shape: "rectangle", color: "green" },
      },
      {
        id: "processor-b",
        type: "canvas",
        position: { x: 470, y: 260 },
        width: 120,
        height: 60,
        style: { width: 120, height: 60 },
        data: { label: "Processor B", shape: "rectangle", color: "cyan" },
      },
      {
        id: "elasticsearch",
        type: "canvas",
        position: { x: 690, y: 55 },
        width: 90,
        height: 110,
        style: { width: 90, height: 110 },
        data: { label: "Elasticsearch", shape: "cylinder", color: "default" },
      },
      {
        id: "analytics",
        type: "canvas",
        position: { x: 695, y: 240 },
        width: 100,
        height: 100,
        style: { width: 100, height: 100 },
        data: { label: "Analytics Dashboard", shape: "diamond", color: "purple" },
      },
    ],
    edges: [
      {
        id: "e-pub-broker",
        source: "publisher",
        target: "broker",
        type: "canvasEdge",
      },
      {
        id: "e-broker-proca",
        source: "broker",
        target: "processor-a",
        type: "canvasEdge",
      },
      {
        id: "e-broker-procb",
        source: "broker",
        target: "processor-b",
        type: "canvasEdge",
      },
      {
        id: "e-proca-es",
        source: "processor-a",
        target: "elasticsearch",
        type: "canvasEdge",
      },
      {
        id: "e-procb-analytics",
        source: "processor-b",
        target: "analytics",
        type: "canvasEdge",
      },
    ],
  },
];
